# Generated by Django 4.0.7 on 2025-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
